# Add awaiting review label to all PRs-
awaiting_review:
- any: ['./*', 'bot/*', '.github/*']
# Add documentation label-
documentation:
- any: ['.all-contributorsrc', './*.md', './.github/*/*']
- all: ['!.github/workflows/*', '!.github/resources/*']
