# Add awaiting review label to all PRs-
awaiting review:
- any: ['./*', './.*', './*/**/*']
# Add documentation label-
documentation:
- any: ['.all-contributorsrc', '*.md', '.github/**/*', '!.github/workflows/*', '!.github/resources/*']
