# Add awaiting review label to all PRs-
# awaiting_review:
# - any: ['./*', 'bot/*']
# Add documentation label-
documentation: 
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE
# - all: ['!.github/workflows/*', '!.github/resources/*']
