# Add awaiting review label to all PRs-
awaiting_review:
- any: ['./*', 'bot/*']
# Add documentation label-
documentation:
- any: ['.all-contributorsrc', '*.md']
# - all: ['!.github/workflows/*', '!.github/resources/*']
