title = "TearDrops"
version = "0.1.2"

# Project Details
[project]
description = "Discord bot made using discord.py with xp level-up system"
authors = ["Vyvy-vi <chat.vyvy-vi.ninja>"]
repo = "https://github.com/Vyvy-vi/TearDrops"


[dependencies]
python = "^3.7.0"
discord.py = "=1.6.0"
motor = "=2.3.1"
wikipedia = "=1.4.0"
aiohttp = "=3.7.3"
dnspython = "=2.1.0"
jishaku = "1.20.0.220"
dotenv = "0.15.0"

[dev-dependencies]
pylint_runner = "=0.6.0" 
flake8 = "=3.8.4"
