name: Changelog
on:
  push:
    branches:
      - chore/docker-pipenv

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: Vyvy-vi-learns/conventional-changelog-action@ignore
        with:
          github-token: ${{ secrets.CHANGELOG_RELEASE }}
          output-file: "false"
          version-file: "Pipfile"

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
